version : "3.8"

services:
  # backend
  backend:
    build: ./backend
    container_name: finance-backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./backend/data/kb:/app/data/kb
    environment:
      - MODEL_PATH=/app/models/bert_finance
      - KB_PATH=/app/data/kb/finance_vector_db
    restart: always

  # frontend
  frontend:
    build: ./frontend
    container_name: finance-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always